-- Bullseye 1–4W
-- Phase 4S.2 — Canonical Supabase schema
--
-- Purpose:
--   Reproduce the durable database objects required by the validated Phase 4R.5A app.
--   This file contains NO credentials, API keys, project URLs, or owner secrets.
--
-- Safe deployment model:
--   - Intended for a fresh Bullseye Supabase project.
--   - Statements are written to be repeatable where practical.
--   - Do NOT run this against the current production database during Phase 4S.2.
--
-- Current server-side access model:
--   The Streamlit app sends the configured Supabase secret in the `apikey` header.
--   The database-facing role is service_role. anon/authenticated are not granted access
--   to Bullseye's durable tables.

begin;

-- ---------------------------------------------------------------------------
-- 1. Live positions — Phase 4Q.5
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_positions (
    owner_id text not null,
    position_key text not null,
    ticker text not null,
    position_state text not null default 'Entered / Live Position',
    entry double precision not null,
    initial_shares double precision not null default 0,
    remaining_shares double precision not null default 0,
    realized_pl double precision not null default 0,
    original_stop double precision not null default 0,
    current_stop_input double precision not null default 0,
    highest_r double precision,
    highest_state text,
    protective_floor double precision,
    last_live_mark double precision,
    last_action text,
    updated_at timestamptz not null default now(),
    primary key (owner_id, position_key)
);

create index if not exists bullseye_positions_owner_ticker_updated_idx
    on public.bullseye_positions (owner_id, ticker, updated_at desc);

alter table public.bullseye_positions enable row level security;
revoke all on table public.bullseye_positions from anon, authenticated;
grant select, insert, update, delete on table public.bullseye_positions to service_role;


-- ---------------------------------------------------------------------------
-- 2. Saved candidate watchlist — Phase 4Q.8A
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_candidates (
    owner_id text not null,
    ticker text not null,
    candidate_action text,
    action_reason text,
    bullseye_score double precision,
    signal_tier text,
    bullseye_action text,
    setup_quality double precision,
    rsi double precision,
    dist_20ma_pct double precision,
    rel_vol double precision,
    rs_vs_spy_20d double precision,
    market_regime double precision,
    current_mark double precision,
    entry_low double precision,
    entry_high double precision,
    breakout_reference double precision,
    invalidation_reference double precision,
    target_1r double precision,
    target_2r double precision,
    target_3r double precision,
    risk_pct double precision,
    entry_mode text,
    updated_at timestamptz not null default now(),
    primary key (owner_id, ticker)
);

create index if not exists bullseye_candidates_owner_updated_idx
    on public.bullseye_candidates (owner_id, updated_at desc);

alter table public.bullseye_candidates enable row level security;
revoke all on table public.bullseye_candidates from anon, authenticated;
grant select, insert, update, delete on table public.bullseye_candidates to service_role;


-- ---------------------------------------------------------------------------
-- 3. Closed-trade archive — Phase 4Q.9A / 4Q.9G final read model
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_closed_trades (
    id bigint generated by default as identity primary key,
    owner_id text not null,
    source_position_key text not null,
    ticker text not null,
    position_state text not null default 'Closed Trade',
    entry double precision not null default 0,
    initial_shares double precision not null default 0,
    remaining_shares double precision not null default 0,
    realized_pl double precision not null default 0,
    original_stop double precision,
    current_stop_input double precision,
    highest_r double precision,
    highest_state text,
    protective_floor double precision,
    last_live_mark double precision,
    last_action text,
    final_exit_price double precision,
    exit_reason text,
    notes text,
    source_updated_at timestamptz,
    closed_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create unique index if not exists bullseye_closed_trades_owner_source_uq
    on public.bullseye_closed_trades (owner_id, source_position_key);

create index if not exists bullseye_closed_trades_owner_closed_idx
    on public.bullseye_closed_trades (owner_id, closed_at desc);

create index if not exists bullseye_closed_trades_owner_ticker_idx
    on public.bullseye_closed_trades (owner_id, ticker, closed_at desc);

alter table public.bullseye_closed_trades enable row level security;
revoke all on table public.bullseye_closed_trades from anon, authenticated;
grant select on table public.bullseye_closed_trades to service_role;


-- ---------------------------------------------------------------------------
-- 4. Atomic Close & Archive RPC — Phase 4Q.9A
-- ---------------------------------------------------------------------------
create or replace function public.bullseye_close_trade(
    p_owner_id text,
    p_position_key text,
    p_final_exit_price double precision,
    p_final_realized_pl double precision,
    p_exit_reason text default null,
    p_notes text default null
)
returns table (
    closed_trade_id bigint,
    closed_ticker text,
    closed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_pos public.bullseye_positions%rowtype;
    v_closed_id bigint;
    v_closed_at timestamptz;
begin
    select *
      into v_pos
      from public.bullseye_positions
     where owner_id = p_owner_id
       and position_key = p_position_key
     for update;

    if not found then
        raise exception 'No live Bullseye position found for owner_id=% position_key=%',
            p_owner_id, p_position_key;
    end if;

    if coalesce(v_pos.position_state, '') <> 'Entered / Live Position' then
        raise exception 'Position % is not an Entered / Live Position (state=%)',
            p_position_key, coalesce(v_pos.position_state, '<null>');
    end if;

    if p_final_exit_price is null or p_final_exit_price <= 0 then
        raise exception 'Final exit price must be greater than zero.';
    end if;

    insert into public.bullseye_closed_trades (
        owner_id,
        source_position_key,
        ticker,
        position_state,
        entry,
        initial_shares,
        remaining_shares,
        realized_pl,
        original_stop,
        current_stop_input,
        highest_r,
        highest_state,
        protective_floor,
        last_live_mark,
        last_action,
        final_exit_price,
        exit_reason,
        notes,
        source_updated_at,
        closed_at
    )
    values (
        v_pos.owner_id,
        v_pos.position_key,
        v_pos.ticker,
        'Closed Trade',
        coalesce(v_pos.entry, 0),
        coalesce(v_pos.initial_shares, 0),
        0,
        coalesce(p_final_realized_pl, v_pos.realized_pl, 0),
        v_pos.original_stop,
        v_pos.current_stop_input,
        v_pos.highest_r,
        v_pos.highest_state,
        v_pos.protective_floor,
        v_pos.last_live_mark,
        v_pos.last_action,
        p_final_exit_price,
        nullif(trim(coalesce(p_exit_reason, '')), ''),
        nullif(trim(coalesce(p_notes, '')), ''),
        v_pos.updated_at,
        now()
    )
    returning id, bullseye_closed_trades.closed_at
      into v_closed_id, v_closed_at;

    delete from public.bullseye_positions
     where owner_id = p_owner_id
       and position_key = p_position_key;

    closed_trade_id := v_closed_id;
    closed_ticker := v_pos.ticker;
    closed_at := v_closed_at;
    return next;
end;
$$;

revoke all on function public.bullseye_close_trade(
    text, text, double precision, double precision, text, text
) from public;

revoke all on function public.bullseye_close_trade(
    text, text, double precision, double precision, text, text
) from anon;

revoke all on function public.bullseye_close_trade(
    text, text, double precision, double precision, text, text
) from authenticated;

grant execute on function public.bullseye_close_trade(
    text, text, double precision, double precision, text, text
) to service_role;


-- ---------------------------------------------------------------------------
-- 5. Early-warning scanner snapshots — Phase 4R.2 + 4R.3 columns
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_early_warning_snapshots (
    id bigint generated by default as identity primary key,
    owner_id text not null,
    scan_id text not null,
    scanned_at timestamptz not null default now(),
    ticker text not null,
    stage text not null,
    stage_rank integer not null default 0,
    bullseye_score double precision,
    gap_to_90 double precision,
    readiness integer,
    why text,
    next_trigger text,
    price double precision,
    accelerator double precision,
    core_count integer,
    momentum_accel double precision,
    rel_vol double precision,
    rs_vs_spy_20d double precision,
    rsi double precision,
    dist_20ma_pct double precision,
    signal_tier text,
    action text,
    action_rank integer,
    signal_badges text,
    market_regime text,
    opportunity_state text,
    opportunity_icon text,
    opportunity_rank integer,
    opportunity_why text,
    opportunity_next_trigger text,
    created_at timestamptz not null default now(),
    constraint bullseye_early_warning_snapshots_stage_check
        check (stage in ('BACKGROUND', 'WATCH', 'DEVELOPING', 'QUALIFIED', 'Unavailable'))
);

-- Compatibility for a database created from the original 4R.2 schema.
alter table public.bullseye_early_warning_snapshots
    add column if not exists opportunity_state text,
    add column if not exists opportunity_icon text,
    add column if not exists opportunity_rank integer,
    add column if not exists opportunity_why text,
    add column if not exists opportunity_next_trigger text;

create unique index if not exists bullseye_early_warning_snapshots_run_ticker_uq
    on public.bullseye_early_warning_snapshots (owner_id, scan_id, ticker);

create index if not exists bullseye_early_warning_snapshots_owner_ticker_time_idx
    on public.bullseye_early_warning_snapshots (owner_id, ticker, scanned_at desc);

create index if not exists bullseye_early_warning_snapshots_owner_time_idx
    on public.bullseye_early_warning_snapshots (owner_id, scanned_at desc);

alter table public.bullseye_early_warning_snapshots enable row level security;
revoke all on table public.bullseye_early_warning_snapshots from anon, authenticated;
grant select, insert, update on table public.bullseye_early_warning_snapshots to service_role;
grant usage, select on sequence public.bullseye_early_warning_snapshots_id_seq to service_role;


-- ---------------------------------------------------------------------------
-- 6. Durable account settings — Phase 4R.2F
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_app_settings (
    owner_id text primary key,
    account_size double precision not null default 25000.0
        check (account_size >= 0),
    updated_at timestamptz not null default now()
);

alter table public.bullseye_app_settings enable row level security;
revoke all on table public.bullseye_app_settings from anon, authenticated;
grant select, insert, update on table public.bullseye_app_settings to service_role;


-- ---------------------------------------------------------------------------
-- 7. Prospective candidate outcome journal — Phase 4R.5 / 4R.5A
-- ---------------------------------------------------------------------------
create table if not exists public.bullseye_candidate_outcomes (
    owner_id text not null,
    ticker text not null,
    tracking_status text not null default 'TRACKING',
    tracked_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    initial_stage text,
    initial_opportunity_state text,
    initial_score double precision,
    initial_price double precision,
    latest_stage text,
    latest_opportunity_state text,
    latest_score double precision,
    latest_price double precision,
    entry_low double precision,
    entry_high double precision,
    breakout_reference double precision,
    invalidation_reference double precision,
    target_1r double precision,
    target_2r double precision,
    target_3r double precision,
    max_observed_price double precision,
    min_observed_price double precision,
    entry_zone_seen_at timestamptz,
    qualified_seen_at timestamptz,
    breakout_seen_at timestamptz,
    target_1r_seen_at timestamptz,
    target_2r_seen_at timestamptz,
    target_3r_seen_at timestamptz,
    invalidation_seen_at timestamptz,
    primary key (owner_id, ticker)
);

alter table public.bullseye_candidate_outcomes enable row level security;
revoke all on table public.bullseye_candidate_outcomes from anon, authenticated;
grant select, insert, update, delete on table public.bullseye_candidate_outcomes to service_role;

commit;
